package Vista;



import Controller.ControllerCRUD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis
 */
public class PanelCRUD extends javax.swing.JPanel {

    
       public PanelCRUD() {
        initComponents();
        this.inicializarPanel();
        ControllerCRUD.cargarTabla(tablaVehiculos);
        if(ControllerCRUD.comprobarAdmin()){
            llenarComboBox(ControllerCRUD.getNombresClientes());
        }
       
    }

 
private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {										
 
	 // TODO add your handling code here:
 
}										
 
private void llenarComboBox(ArrayList<String> nombreClientes){
    comboBox.setVisible(true);
    for(String cadaNombre: nombreClientes){
        comboBox.addItem(cadaNombre);
    }
}
 
 
private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {										
	
    ControllerCRUD.insertarVehiculo(this, tablaVehiculos);

}	

private void btModificarActionPerformed(java.awt.event.ActionEvent evt){
    ControllerCRUD.modificarVehiculo(this,tablaVehiculos);
    txtMarca.setText("");
    txtModelo.setText("");
    txtMatricula.setText("");

}

private void btBorrarActionPerformed(java.awt.event.ActionEvent evt){
    
    ControllerCRUD.borrarVehiculo(this, tablaVehiculos);
    
}
 
 
 
public javax.swing.JTextField getTxtMatricula() {
	return txtMatricula;
}



public void setTxtMatricula(javax.swing.JTextField txtMatricula) {
	this.txtMatricula = txtMatricula;
}



public javax.swing.JTextField getTxtMarca() {
	return txtMarca;
}



public void setTxtMarca(javax.swing.JTextField txtMarca) {
	this.txtMarca = txtMarca;
}



public javax.swing.JTextField getTxtModelo() {
	return txtModelo;
}



public void setTxtModelo(javax.swing.JTextField txtModelo) {
	this.txtModelo = txtModelo;
}
				
 
private javax.swing.JButton btMod;
 
private javax.swing.JButton btRegistrar;

private  javax.swing.JButton btBorrar;

private javax.swing.JComboBox<String> comboBox; 

private javax.swing.JLabel jLabel1;
 
private javax.swing.JLabel jLabel2;
 
private javax.swing.JLabel jLabelMatricula;
 
private javax.swing.JScrollPane jScrollPane1;
 
private javax.swing.JTable tablaVehiculos;
 
private javax.swing.JTextField txtMatricula;
 
private javax.swing.JTextField txtMarca;
 
private javax.swing.JTextField txtModelo;
    /**
     * Creates new form PanelCRUD
     */
 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


private void inicializarPanel() {
 
 
        comboBox = new javax.swing.JComboBox<>();
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        comboBox.setVisible(false);
        comboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener el elemento seleccionado
                String selectedItem = (String) comboBox.getSelectedItem();
                
                // Llamar a la función y pasarle el elemento seleccionado
                ControllerCRUD.cargarTablaAdmin(selectedItem, tablaVehiculos);
            }
        });
        
	 jLabel1 = new javax.swing.JLabel();
 
	 jScrollPane1 = new javax.swing.JScrollPane();
 
	 tablaVehiculos = new javax.swing.JTable();
 
	 txtMarca = new javax.swing.JTextField();
 
	 txtModelo = new javax.swing.JTextField();
 
	 jLabel2 = new javax.swing.JLabel();
 
	 jLabelMatricula = new javax.swing.JLabel();
 
	 txtMatricula = new javax.swing.JTextField();
 
	 btRegistrar = new javax.swing.JButton();
 
	 btMod = new javax.swing.JButton();
         
         btBorrar = new javax.swing.JButton();

	 jLabel1.setText("Marca");
  
	 tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
 
		 new Object [][] {
 
			 {null, null, null, null},
 
			 {null, null, null, null},
 
			 {null, null, null, null},
 
			 {null, null, null, null}
 
		 },
 
		 new String [] {
 
			 "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
 
		 }
 
	 ));
	jScrollPane1.setViewportView(tablaVehiculos);
 
        ListSelectionModel selectionModel = tablaVehiculos.getSelectionModel();

        // Agregar un ListSelectionListener para manejar los clics en la tabla
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Obtener la fila seleccionada
                    int selectedRow = tablaVehiculos.getSelectedRow();
                    if (selectedRow != -1) {
                        // Hacer algo con la fila seleccionada, por ejemplo, obtener datos de la fila
                        String marca = tablaVehiculos.getValueAt(selectedRow, 0).toString();
                        String modelo = tablaVehiculos.getValueAt(selectedRow, 1).toString();
                        String matricula = tablaVehiculos.getValueAt(selectedRow, 2).toString();
                        String propietario = tablaVehiculos.getValueAt(selectedRow,3).toString();
                        txtMarca.setText(marca);
                        txtModelo.setText(modelo);
                        txtMatricula.setText(matricula);

                    }
                }
            }
        });
 
	 txtMarca.setName("marca"); // NOI18N

	 txtModelo.setToolTipText("");
 
	 txtModelo.setName("modelo"); // NOI18N

	 jLabel2.setText("Modelo");

	 jLabelMatricula.setText("Matricula"); 
 
	 txtMatricula.setToolTipText("");
 
	 btRegistrar.setText("Registrar");
 
	 btRegistrar.setActionCommand("btRegistrar");
 
	 btRegistrar.setName("btRegistrar"); // NOI18N
 
	 btRegistrar.addActionListener(new java.awt.event.ActionListener() {
 
		 public void actionPerformed(ActionEvent e) {
 
			 btRegistrarActionPerformed(e);
 
		 }
 
	 });
 
 
 
	 btMod.setText("Modificar");
 
	 btMod.setToolTipText("");
 
	 btMod.setName("Modificar"); // NOI18N
         
         btMod.addActionListener(new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e) {
                 btModificarActionPerformed(e);
             }
         
         });
 
 
        btBorrar.setText("Borrar");
        btBorrar.setToolTipText("");
        btBorrar.setName("btBorrar");
        
        btBorrar.addActionListener(new ActionListener(){
            
                public void actionPerformed(ActionEvent e) {
 
			 btBorrarActionPerformed(e);
 
		 }
        
        });
        

           javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
           layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addContainerGap()
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGroup(layout.createSequentialGroup()
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                               .addComponent(jLabel1)
                               .addComponent(jLabel2)
                               .addComponent(jLabelMatricula))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                               .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)  // Set the size for txtModelo
                               .addGroup(layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                       .addComponent(txtMarca)
                                       .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                       .addComponent(btRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(btMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(btBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                   .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           );

           layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addContainerGap()
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(layout.createSequentialGroup()
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                               .addComponent(jLabel1)
                               .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                               .addComponent(jLabel2)
                               .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))  // Set the size for txtModelo
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                               .addComponent(jLabelMatricula)
                               .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                       .addGroup(layout.createSequentialGroup()
                           .addComponent(btRegistrar)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(btMod)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(btBorrar)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addGap(26)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(32, Short.MAX_VALUE))
           );

           this.setLayout(layout);

 
 
	 
 
}// </editor-fold>	



}
